run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - whitespace
    - goconst
    - gochecknoinits
    - gocheckcompilerdirectives
    - containedctx
    - errname
    - ineffassign
    - gosimple
    - gofumpt
    - unused
    - govet
    - errcheck
    - lll
linters-settings:
  lll:
    line-length: 120
    tab-width: 2