version: "3.8"
services:
  back:
    build:
      context: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "7000:5432"
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
