version: "3.8"
services:
  front:
    container_name: front
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - back
  back:
    container_name: back
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
